name: CI & Release

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

env:
  DOCKER_BUILDKIT: 1
  # Enable debug logging for actions
  ACTIONS_RUNNER_DEBUG: true

jobs:
  test:
    name: 'Lint, Type Check, Test, & Build'
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node_version: ['lts/*']
        pnpm_version: ['latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm_version }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: |
          pnpm lint
          pnpm format

      - name: Type Check
        run: pnpm typecheck

      - name: Build
        run: pnpm build

      - name: Test
        run: |
          pnpm prepare-test
          pnpm test

    # Generate GitHub Release Changelog
  Changelog:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Generate Changelog
        run: npx changelogithub --no-group
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: 'Publish: npm Registry'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 'Publish'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm publish --access=public --registry=https://registry.npmjs.org --no-git-checks

  publish-gpr:
    name: 'Publish: GitHub Package Registry'
    needs: [test]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Update ~/.npmrc
        run: |
          echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      # GitHub Package Registry requires the package name to be scoped to the repository
      - name: Update package.json "name"
        run: |
          sed -i 's/"name": ".*"/"name": "@o-az\/xtsz"/' package.json

      - name: 'Publish'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm publish --access public --registry https://npm.pkg.github.com --no-git-checks
