name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  # Enable debug logging for actions
  ACTIONS_RUNNER_DEBUG: true

jobs:
  changelog:
    name: 'Generate Changelog'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Generate Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bunx changelogithub --no-group
        continue-on-error: true

  publish-npm:
    name: 'Publish: npm Registry'
    needs: [changelog]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: 'Publish'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm publish --access=public --registry=https://registry.npmjs.org --no-git-checks

  publish-gpr:
    name: 'Publish: GitHub Package Registry'
    needs: [changelog]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Update ~/.npmrc
        run: |
          echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      # GitHub Package Registry requires the package name to be scoped to the repository
      - name: Update package.json "name"
        run: |
          sed -i 's/"name": ".*"/"name": "@o-az\/xtsz"/' package.json

      - name: 'Publish'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm publish --access public --registry https://npm.pkg.github.com --no-git-checks
